config/routes.rb
Yestrak::Application.routes.draw do

  constraints :subdomain => PARTNER_SUBDOMAIN do
    devise_for :partner_masters, :controllers => {:confirmations => 'confirmations'}
    devise_scope :partner_master do
      put "/confirm" => "confirmations#confirm"
    end

    namespace :partners do
      resources :dashboard do
        collection do
          match 'upload_logo' => "dashboard#upload_logo"
        end
      end
      resources :stats do
        collection do
          match "daterange_selector" => "stats#daterange_selector", as: "daterange_selector"
        end
      end

      resources :statements do #, only: [:index]
        collection do
          match "daterange_selector" => "statements#daterange_selector", as: "daterange_selector"
          post "paid_commission/:commission_id" => "statements#paid_commission", as: "paid_commission"
          post "paid_bonus" => "statements#paid_bonus", as: "paid_bonus"
  
        end
      end
      resources :account do
        match 'update' => "account#update"
        get :verify_paypal_account
      end
      resources :custom_links, only: [:index] do
        collection do
          match "edit_partner_page" => "custom_links#edit_partner_page", as: "edit_partner_page"
        end
      end
      resources :partner_docusign do
        collection do
          match 'upload_agreement' => 'partner_docusign#upload_agreement'
          match 'embedded_signing' => "partner_docusign#embedded_signing"
          match 'docusign_response' => "partner_docusign#docusign_response"
        end
      end
      resources :partner_helps
      match 'help_confirmation' => 'partner_helps#help_confirmation'
    end

    # Partner User change password after login
    get "partner_users/edit_user_password" => "partner_users#edit_user_password"
    post "partner_users/update_user_password" => "partner_users#update_user_password"
    get "partner_users/login/:auth_token" => "partner_users#login", as: 'login_from_admin_site'

    match "partner_users/check_current_password" => "partner_users#check_current_password"

    root :to => "partners/dashboard#index"
  end

  constraints :subdomain => ADMIN_SUBDOMAIN do
    ActiveAdmin.routes(self)
    devise_for :admin_users, ActiveAdmin::Devise.config.merge(:path => '')
    resources :recordings do
      member do
        get 'admin_download'
      end
    end
  end

  get "tags/index"
  # devise_for :users, controllers: {sessions: "sessions"}
  # API controllers for wordpress marketing site 
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1 do
      scope '/blog_details' do
        post 'fetch_blog_details' => 'blog_details#fetch_blog_details'
        post 'delete_blog_detail' => 'blog_details#delete_blog_detail'
      end
      scope '/contacts' do
        match 'create' => 'contacts#create'
      end
      scope 'subscription' do
        match 'create' => 'subscription#create'
        match 'validate_email' => 'subscription#validate_email'
        match 'discount_amount' => 'subscription#discount_amount'
      end
      scope 'partner' do
         match 'partner_detail' => 'partner#partner_detail'
         match 'partner_logo' => 'partner#partner_logo'
         match 'partner_landing_page_click' => 'partner#partner_landing_page_click'
      end
    end
  end

  scope '/webhooks' do
    post '/process' => 'webhooks#handle' #, :as => :process_webhook, :via => :post
    get '/process' => 'webhooks#verify' #, :as => :verify_webhook, :via => :get
  end

  # Settings allowed to owner or admin
  namespace :settings do
    resources :dashboard, only: [:index]
    resources :businesses, except: [:show] do
      collection do
        match "check_business_name" => "businesses#check_business_name"
      end
    end
    resources :phone_scripts, except: [:show] do
      member do
        get 'pick_number'
        put 'choose_number'
        post 'search_local_number'
        post 'search_tollfree_number'
        get 'set_script'
        put 'update_script'
        put 'complete'
        get 'routing_notification'
      end
      get 'check_for_uniq_name', on: :collection
    end
    resources :voicemails, except: [:show] do
      member do
        get 'pick_number'
        put 'choose_number'
        post 'search_local_number'
        post 'search_tollfree_number'
      end
      get 'check_for_uniq_name', on: :collection
    end
    resources :phone_menus, except: [:show] do
      member do
        get 'pick_number'
        put 'choose_number'
        post 'search_local_number'
        post 'search_tollfree_number'
      end
      get 'check_for_uniq_name', on: :collection
    end
    resources :call_recordings, only: [:index] do
      put 'update_recordings', on: :collection
    end
    resources :calendars, except: [:show] do
      collection do
        match "add_appointment_details" => "calendars#add_appointment_detail"
        match "check_duplicate_name" => "calendars#check_duplicate_name"
        match :remove_calendar_hour
        match "ical" => "calendars#ical", as: :ical
      end
    end
    resources :contacts, except: [:show] do
      # get :autocomplete_note_name, :on => :collection
      collection do
        # match "save_contact_settings" => "contacts#create_contact_settings", as: "save"
        match "add_status_label" => "contacts#add_status_label"
        match "add_tag" => "contacts#add_tag"
        get "delete_status/:id" => "contacts#delete_status"
        get :export_contacts
      end
    end
    resources :users, except: [:show] do
      collection do
        match "check_duplicate_email" => "users#check_duplicate_email"
        match "my_account" => "users#my_account"
        get :user_cancellation
        post :cancellation
        post :submit_suggestion
      end
    end
    resources :billings, except: [:show] do
      collection do
        match "upgrade_downgrade" => "billings#upgrade_downgrade"
        match "view_all_payments" => "billings#view_all_payments"
        match "view_invoice/:id" => "billings#view_invoice", as: :view_invoice
        match "download_invoice" => "billings#download_invoice"
      end
    end
  end
  
  resources :voicemail do
    collection do
      match "daterange_selector" => "voicemail#daterange_selector", as: "daterange_selector"
    end
  end
  # Calendar view
  resources :calendars, except: [:show] do
    collection do
      post :appoint_view
      get :appointment_view_month
      get :appointment_view_week
      get :appointment_day
      get :block_timing_modification
      post :list_calendars_appointments
    end
  end
  scope :calendars do
    get '(/:year(/:month))', to: 'calendars#index', :as => :calendars, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
    match 'weekly(/:date)' => 'calendars#weekly', :as => :weekly
    get 'daily(/:date)' => 'calendars#daily', :as => :daily
  end

  # Google Sync
  match "/auth/:provider/callback" => "calendars#google_sync"
  match "cancel_google_sync" => 'calendars#cancel_google_sync', as: :cancel_google_sync

  # Appointments
  resources :appointments do
    match 'get_contact_detail/:contact_id' => 'appointments#get_contact_detail', as: :get_contact_detail
    collection do
      match "is_valid_time" => "appointments#is_valid_time"
    end
  end

  # Dashboard notification
  resources :notifications, only: [:index] do
    collection do
      match "daterange_selector" => "notifications#daterange_selector", as: "daterange_selector"
      match "create_user_notification_entry" => "notifications#create_user_notification_entry"
    end
  end

  resources :registrations, only: [:index] do
    collection do
      # get "rejoin/:auth_token" => "registrations#rejoin", as: "rejoin"
      get :rejoin
      post :process_rejoin
      post :check_coupen
    end
  end


  resources :call_recordings do
    collection do
      match "daterange_selector" => "call_recordings#daterange_selector", as: "daterange_selector"
    end
  end

  match 'voicemail/:sid' => 'call_recordings#voicemail', as: 'voicemail_recording'
  match 'voicemail_test/:sid' => 'call_recordings#voicemail_test'

  # Contacts display
  resources :contacts, except: [:show] do
    collection do
      get "autocomplete_contact_first_name" => "contacts#autocomplete_contact_first_name"
      get "autocomplete_tag_name" => "contacts#autocomplete_tag_name"
      get "add_phone_to_contact" => "contacts#add_phone_to_contact"
      get "add_email_to_contact" => "contacts#add_email_to_contact"
      get "destroy_phone/:phone_id" => "contacts#destroy_phone"
      get "destroy_email/:email_id" => "contacts#destroy_email"
      post "find_statuslabels" => "contacts#find_statuslabels"
      match 'view_all_notes/:id' => 'contacts#view_all_notes', as: "view_all_notes"
      match 'destroy_note/:note_id' => 'contacts#destroy_note', as: "destroy_note"
    end
  end
  
  # MANAGE PHONE CALLS
  scope '/manage_calls', defaults: {format: 'xml'} do
    match 'phone_script' => 'manage_phone_calls#phone_script', as: 'manage_phone_script'
    match 'phone_menu' => 'manage_phone_calls#phone_menu', as: 'manage_phone_menu'
    match 'voicemail' => 'manage_phone_calls#voicemail', as: 'manage_voicemail'
    match 'gather_digits' => 'manage_phone_calls#gather_digits'
    match 'record_call' => 'manage_phone_calls#record_call'
    match 'call_complete' => 'manage_phone_calls#call_complete', as: 'manage_call_complete'
    match 'download(/:id)' => 'call_recordings#download', as: :download_recording
  end

  # calendar paths
  scope '/calendar' do
    get '(/:year(/:month))', to: 'calendars#index', :as => :calendars, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
    match 'weekly(/:date)' => 'calendars#weekly', :as => :weekly
    get 'daily(/:date)' => 'calendars#daily', :as => :daily
  end
  resources :appointments, except: [:index, :show]

  # User change password after login
  get "users/edit_user_password" => "users#edit_user_password"

app/controllers/api/v1/partner_controller.rb
module Api
  module V1
    class PartnerController < ApplicationController
      respond_to :json
      skip_before_filter :logged_in, :set_defaults, :set_current_tenant

      def partner_detail
        coupon = DiscountMaster.find_by_coupon_code_and_active(params[:coupon_code],1)
        if coupon
          partner = coupon.partner_master
          if partner

            partner_landing = partner.partner_landing
            if partner_landing.present?
              content = partner_landing.content
            else
              content = ''
            end

            result = {success: true, partner_coupon_code: coupon.coupon_code, id: partner.id, first_name: partner.first_name, last_name: partner.last_name, content: content }
          else
            result = {success: false, message: 'Partner not found'}
          end
        else
          result = {success: false, message: 'Coupon not found'}
        end
        render json: result
      end

      def partner_logo
        coupon = DiscountMaster.find_by_coupon_code_and_active(params[:coupon_code],1)
        if coupon
          partner = coupon.partner_master
          if partner
            partner_logo = partner.partner_logo
            if partner_logo
              redirect_to ("#{root_url.chop}" + "#{partner_logo.logo.url}")
            else
              #render json: {success: false, message: 'Logo not found'}
              redirect_to ("#{root_url}default_logo.png")
            end
          else
            render json: {success: false, message: 'Partner not found'}
          end
        else
          render json: {success: false, message: 'Coupon not found'}
        end
      end
      def partner_landing_page_click
        coupon = DiscountMaster.find_by_coupon_code_and_active(params[:coupon_code],1)
        if coupon
          partner = coupon.partner_master_id
          if partner
            partner_state = PartnerStat.find_by_ip_address_and_partner_master_id(params[:ip_address], coupon.partner_master_id)
              if partner_state.present?
                partner_state.increment!(:clicks)
                render json: {success: true, message: 'partner state updated'}
              else
                partner_state = PartnerStat.create(:ip_address => params[:ip_address], :partner_master_id => coupon.partner_master_id, :clicks => 1)
                render json: {success: true, message: 'partner state created'}
              end
          else
            render json: {success: false, message: 'Partner not found'}
          end
        else
          render json: {success: false, message: 'Coupon not found'}
        end  
      end

    end
  end
end

app/controllers/partners/account_controller.rb
class Partners::AccountController < ApplicationController
  layout 'partners'
  # PAYMENT_TYPE = {"PAYPAL"=>"PAYPAL" , "BY CHECK" => "BY CHECK"}
  before_filter :check_doc_sign

  def index
    @paypal_type = ["PAYPAL", "BY CHECK"]
    @partner_master = PartnerMaster.find(params[:id])
    @partner_master.phone_number || @partner_master.build_phone_number
    @partner_master.address || @partner_master.build_address
    @paypal_info = PartnerPaymentInformation.find_by_partner_master_id(@partner_master.id) || PartnerPaymentInformation.new
  end

  def update
    @partner_master = PartnerMaster.find(params[:partner_master][:id])
    if params[:us_state].present?
      params[:partner_master][:address_attributes][:state] = params[:us_state]
    elsif params[:ca_state].present?
      params[:partner_master][:address_attributes][:state] = params[:ca_state]
    elsif params[:other_state].present?
      params[:partner_master][:address_attributes][:state] = params[:other_state]
    end

    if @partner_master.update_attributes!(params[:partner_master])
      redirect_to partners_account_index_path(id: params[:partner_master][:id]), notice: "Your account information saved successfully"
    else
      render :index
    end
    if params[:payment_type].present?
      @paypal_info = PartnerPaymentInformation.find_by_partner_master_id(params[:partner_master][:id])
      if @paypal_info.present?
        @paypal_info = @paypal_info.update_attributes(:payment_type => params[:payment_type], :paypal_email => params[:partner_payment_information][:paypal_email])
      else
        @paypal_info = PartnerPaymentInformation.create(:partner_master_id => params[:partner_master][:id], :payment_type => params[:payment_type], :paypal_email => params[:partner_payment_information][:paypal_email])
      end
    end
  end

  def verify_paypal_account
    respond_to do |format|
      format.json { render :json => PaypalApi.verify_paypal_account(params[:paypal_email]).success? }
    end
  end

  private

  def check_doc_sign
    if !current_partner_master.doc_sign
      flash[:alert] = "Please execute the partnership agreement to proceed. If you have any query, contact to YesTrak support team at support@yestrak.com"
      redirect_to partners_partner_docusign_index_path
    end
  end
end

app/controllers/partners/partner_helps_controller.rb
class Partners::PartnerHelpsController < ApplicationController
	layout 'partners'
	def index
    @partner_help = PartnerHelp.new
    render "new"
  end

  def new
  end

  def create
    params[:partner_help][:partner_master_id] = current_partner_master.id
    @partner_help = PartnerHelp.new(params[:partner_help])
    if @partner_help.save
      # =========== M A I L E R ============
      ClientMailer.partner_help_notice(@partner_help.id).deliver
      # =========== M A I L E R ============

      redirect_to partners_help_confirmation_path, notice: "We just received your question. A YesTrak representative will be in touch shortly with an answer."
    else
      render :new
    end
  end

  def help_confirmation
  end
end

app/helpers/partners/account_helper.rb
module Partners::AccountHelper
end

app/helpers/partners/custom_links_helper.rb
module Partners::CustomLinksHelper
end

app/helpers/partners/dashboard_helper.rb
module Partners::DashboardHelper
end

app/helpers/partners/partner_docusign_helper.rb
module Partners::PartnerDocusignHelper
end

app/helpers/partners/partner_helps_helper.rb
module Partners::PartnerHelpsHelper
end

app/helpers/partners/statements_helper.rb
module Partners::StatementsHelper
	
  def partner_statement_no_records
    concat content_tag(:section, class: 'table_row') {
      content_tag(:div, class: 'no_data') {
        content_tag(:div, 'No Records Found')
      }
    }
  end

end

app/helpers/partners/stats_helper.rb
module Partners::StatsHelper
	def partner_state_no_records
    haml_tag :table do
      haml_tag :tr do
        haml_tag :td, {:class => 'cell'} do
          haml_tag :td do
            haml_concat "No Record Found"
          end
        end
    end
  end
  end
end

app/views/partners/stats/_currently_viewing.html.haml
%section.currenty_viewing
  %span{:id=>'span_currenty_viewing'}
    = displaying_range

app/views/partners/stats/_custom_filters.html.haml
%ul.dateRange
  %li
    = collection_select(:partner_state_records_search, :date, CustomFilter::DATE_RANGE, :first, :last, :include_blank => 'All', :selected => '')
    %input#search_date_from{name: "search[date_from]", type: "hidden"}/
    %input#search_date_to{name: "search[date_to]", type: "hidden"}/
  %li
    = link_to 'Custom Range', daterange_selector_partners_stats_path, remote: 'true', class: 'view fancybox fancybox.ajax'

app/views/partners/stats/_daterange_selector.html.haml
.viewContactDetails
  .all_popup.custom_range_main
    .add_new_popup.custom_range_popup
      .add_new_popup_head
        %h1 CUSTOM DATE RANGE
      .add_new
        .custom_range_div_main
          %label.label.label1{for: ""} Select Start Date:
          %label.label.label2{for: ""} Select End Date:
        .custom_range_datepicker
          #custom_range_from
          #custom_range_to
        .action
          = link_to "Save",'javascript:void(0);', onclick: 'filter_custom_stats_range();', class: 'btn_search fancybox'
          = link_to 'Reset', 'javascript:void(0);', onclick: 'reset_custom_stats_range();', class: 'reset fancybox'
        .clear

app/views/partners/stats/_partner_state_list.html.haml
=# partner_state(partner_state, uniques, commission)
- $total = 0
- $comm = 0
- $total_click = 0
- partner_state.each do |ps|
  %section.recordingsbodytable.row
    %section.col1 
      = ps.updated_at.to_date
    %section.col2 
      = ps.clicks
      - $total_click += ps.clicks.to_i 
    %section.col3 
      - uniques.each do |key, value|
        - if key == ps.ip_address
          = value
          - $total += value.to_i
    / %section.col4 
    /   - commission.each do |comm|
    /     - if ps.updated_at.to_date == comm.updated_at.to_date
    /       = number_to_currency(comm.commission)
    /       - $comm += comm.commission.to_i
    /     - else
    /       = ""
%section.tfoot.row
  %section.col1 TOTALS
  %section.col2 
    = $total_click
  %section.col3 
    = $total
  / %section.col4 
  /   = number_to_currency($comm)

app/views/partners/stats/_partner_state_not_found.html.haml
%section.recordingsbodytable.row
	No Record Found
%section.tfoot.row
	%section.col1 TOTALS
	%section.col2 $0.00
	%section.col3 $0.00

app/views/partners/stats/index.html.haml
= javascript_include_tag "highcharts"
= javascript_include_tag "highcharts/highcharts-more"
%section.container
  %section.container_wrapper.graphpage
    %section.columns.clearfix
      %section.column.col-34
        %section.columns.clearfix
          %ul.dateRange
            %li Select the period you want to view:
            %li
              = render partial: 'custom_filters'
    %section.columns.clearfix
      %section.whitebox
        %section.graphpart
          //%div{:id => "container", :style => "min-width: 310px; height: 400px; margin: 0 auto", :data => {:my_data => @clicks}}
          = content_tag "div", :id => "container", :data => {:my_data => @clicks} do
            = #image_tag "partners/graph_image.jpg"
          
        %section.graph_table.recordings_table.visit.clearfix
          %section.recordingsheadtable.thead.row
            %section.col1 DATE
            %section.col2 CLICKS
            %section.col3 UNIQUES
            / %section.col4 TRANSACTIONS
            / %section.col5 COMMISSIONS
            //%section.col5 TOTAL
          - if @partner_state.present?
            = render partial: 'partner_state_list', locals: {partner_state: @partner_state, uniques:@uniques, commission: @commission}
          - else
            = render partial: 'partner_state_not_found'
            
  / eof container
:javascript
/ $(function () {
/     $(document).ready(function() {
/         Highcharts.setOptions({
/             global: {
/                 useUTC: false
/             }
/         });
/         var click = JSON.parse("#{@clicks}");
  

/          var chart;
/        $('#container').highcharts({
/             chart: {
/                 type: 'area'
/             },
/             title: {
/                 text: 'Monthly Average Clicks'
/             },
/            xAxis: {
/             title: {
/                type: 'day',
/                minTickInterval: 1
/                },
/                labels: {
/                     formatter: function() {
/                         return this.value * 35 ;
/                     }
/                 }
            
  
        
/             },
/             yAxis: {
/                 title: {
/                     text: 'Clicks'
/                 },
/                 labels: {
/                     formatter: function() {
/                         return this.value * 20;
/                     }
/                 }
/             },
/             tooltip: {
/                 shared: true,
/                 valueSuffix: 'clicks'
/             },
/             plotOptions: {
/                 area: {
/                     stacking: 'normal',
/                     lineColor: '#4068E0',
/                     lineWidth: 2,
/                     marker: {
/                         lineWidth: 1,
/                         lineColor: '#4068E0'
/                     }
/                 }
/             },
/             series: [{
/                 name: 'Visit',
/                 data: click,
/                 color: 'SKYBLUE'
/             }]
/         });
/     });
/ });

app/views/partners/stats/index.js.erb
$('section.recordingsbodytable').remove()
$("#search_date_from").val("")
$("#search_date_to").val("")
<% if @partner_state.present? %>
	$('section.tfoot.row').remove()
	$("<%= escape_javascript(render(:partial => 'partner_state_list', :locals => { partner_state: @partner_state, uniques: @uniques, commission: @commission })) %>").insertAfter('section.recordingsheadtable')
<% else %>
	$('section.tfoot.row').remove()
	$("<%= escape_javascript(render(:partial => 'partner_state_not_found')) %>").insertAfter('section.recordingsheadtable')
<% end %>

// $('#span_currenty_viewing').append(<%=@displaying_range%>+"-"+<%= Time.new.strftime("%Y-%m-%d %H:%M:%S") %>)