config/routes.rb
Yestrak::Application.routes.draw do

  constraints :subdomain => PARTNER_SUBDOMAIN do
    devise_for :partner_masters, :controllers => {:confirmations => 'confirmations'}
    devise_scope :partner_master do
      put "/confirm" => "confirmations#confirm"
    end

    namespace :partners do
      resources :dashboard do
        collection do
          match 'upload_logo' => "dashboard#upload_logo"
        end
      end
      resources :stats do
        collection do
          match "daterange_selector" => "stats#daterange_selector", as: "daterange_selector"
        end
      end

      resources :statements do #, only: [:index]
        collection do
          match "daterange_selector" => "statements#daterange_selector", as: "daterange_selector"
          post "paid_commission/:commission_id" => "statements#paid_commission", as: "paid_commission"
          post "paid_bonus" => "statements#paid_bonus", as: "paid_bonus"
  
        end
      end
      resources :account do
        match 'update' => "account#update"
        get :verify_paypal_account
      end
      resources :custom_links, only: [:index] do
        collection do
          match "edit_partner_page" => "custom_links#edit_partner_page", as: "edit_partner_page"
        end
      end
      resources :partner_docusign do
        collection do
          match 'upload_agreement' => 'partner_docusign#upload_agreement'
          match 'embedded_signing' => "partner_docusign#embedded_signing"
          match 'docusign_response' => "partner_docusign#docusign_response"
        end
      end
      resources :partner_helps
      match 'help_confirmation' => 'partner_helps#help_confirmation'
    end

    # Partner User change password after login
    get "partner_users/edit_user_password" => "partner_users#edit_user_password"
    post "partner_users/update_user_password" => "partner_users#update_user_password"
    get "partner_users/login/:auth_token" => "partner_users#login", as: 'login_from_admin_site'

    match "partner_users/check_current_password" => "partner_users#check_current_password"

    root :to => "partners/dashboard#index"
  end

  constraints :subdomain => ADMIN_SUBDOMAIN do
    ActiveAdmin.routes(self)
    devise_for :admin_users, ActiveAdmin::Devise.config.merge(:path => '')
    resources :recordings do
      member do
        get 'admin_download'
      end
    end
  end

  get "tags/index"
  # devise_for :users, controllers: {sessions: "sessions"}
  # API controllers for wordpress marketing site 
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1 do
      scope '/blog_details' do
        post 'fetch_blog_details' => 'blog_details#fetch_blog_details'
        post 'delete_blog_detail' => 'blog_details#delete_blog_detail'
      end
      scope '/contacts' do
        match 'create' => 'contacts#create'
      end
      scope 'subscription' do
        match 'create' => 'subscription#create'
        match 'validate_email' => 'subscription#validate_email'
        match 'discount_amount' => 'subscription#discount_amount'
      end
      scope 'partner' do
         match 'partner_detail' => 'partner#partner_detail'
         match 'partner_logo' => 'partner#partner_logo'
         match 'partner_landing_page_click' => 'partner#partner_landing_page_click'
      end
    end
  end

  scope '/webhooks' do
    post '/process' => 'webhooks#handle' #, :as => :process_webhook, :via => :post
    get '/process' => 'webhooks#verify' #, :as => :verify_webhook, :via => :get
  end

  # Settings allowed to owner or admin
  namespace :settings do
    resources :dashboard, only: [:index]
    resources :businesses, except: [:show] do
      collection do
        match "check_business_name" => "businesses#check_business_name"
      end
    end
    resources :phone_scripts, except: [:show] do
      member do
        get 'pick_number'
        put 'choose_number'
        post 'search_local_number'
        post 'search_tollfree_number'
        get 'set_script'
        put 'update_script'
        put 'complete'
        get 'routing_notification'
      end
      get 'check_for_uniq_name', on: :collection
    end
    resources :voicemails, except: [:show] do
      member do
        get 'pick_number'
        put 'choose_number'
        post 'search_local_number'
        post 'search_tollfree_number'
      end
      get 'check_for_uniq_name', on: :collection
    end
    resources :phone_menus, except: [:show] do
      member do
        get 'pick_number'
        put 'choose_number'
        post 'search_local_number'
        post 'search_tollfree_number'
      end
      get 'check_for_uniq_name', on: :collection
    end
    resources :call_recordings, only: [:index] do
      put 'update_recordings', on: :collection
    end
    resources :calendars, except: [:show] do
      collection do
        match "add_appointment_details" => "calendars#add_appointment_detail"
        match "check_duplicate_name" => "calendars#check_duplicate_name"
        match :remove_calendar_hour
        match "ical" => "calendars#ical", as: :ical
      end
    end
    resources :contacts, except: [:show] do
      # get :autocomplete_note_name, :on => :collection
      collection do
        # match "save_contact_settings" => "contacts#create_contact_settings", as: "save"
        match "add_status_label" => "contacts#add_status_label"
        match "add_tag" => "contacts#add_tag"
        get "delete_status/:id" => "contacts#delete_status"
        get :export_contacts
      end
    end
    resources :users, except: [:show] do
      collection do
        match "check_duplicate_email" => "users#check_duplicate_email"
        match "my_account" => "users#my_account"
        get :user_cancellation
        post :cancellation
        post :submit_suggestion
      end
    end
    resources :billings, except: [:show] do
      collection do
        match "upgrade_downgrade" => "billings#upgrade_downgrade"
        match "view_all_payments" => "billings#view_all_payments"
        match "view_invoice/:id" => "billings#view_invoice", as: :view_invoice
        match "download_invoice" => "billings#download_invoice"
      end
    end
  end
  
  resources :voicemail do
    collection do
      match "daterange_selector" => "voicemail#daterange_selector", as: "daterange_selector"
    end
  end
  # Calendar view
  resources :calendars, except: [:show] do
    collection do
      post :appoint_view
      get :appointment_view_month
      get :appointment_view_week
      get :appointment_day
      get :block_timing_modification
      post :list_calendars_appointments
    end
  end
  scope :calendars do
    get '(/:year(/:month))', to: 'calendars#index', :as => :calendars, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
    match 'weekly(/:date)' => 'calendars#weekly', :as => :weekly
    get 'daily(/:date)' => 'calendars#daily', :as => :daily
  end

  # Google Sync
  match "/auth/:provider/callback" => "calendars#google_sync"
  match "cancel_google_sync" => 'calendars#cancel_google_sync', as: :cancel_google_sync

  # Appointments
  resources :appointments do
    match 'get_contact_detail/:contact_id' => 'appointments#get_contact_detail', as: :get_contact_detail
    collection do
      match "is_valid_time" => "appointments#is_valid_time"
    end
  end

  # Dashboard notification
  resources :notifications, only: [:index] do
    collection do
      match "daterange_selector" => "notifications#daterange_selector", as: "daterange_selector"
      match "create_user_notification_entry" => "notifications#create_user_notification_entry"
    end
  end

  resources :registrations, only: [:index] do
    collection do
      # get "rejoin/:auth_token" => "registrations#rejoin", as: "rejoin"
      get :rejoin
      post :process_rejoin
      post :check_coupen
    end
  end


  resources :call_recordings do
    collection do
      match "daterange_selector" => "call_recordings#daterange_selector", as: "daterange_selector"
    end
  end

  match 'voicemail/:sid' => 'call_recordings#voicemail', as: 'voicemail_recording'
  match 'voicemail_test/:sid' => 'call_recordings#voicemail_test'

  # Contacts display
  resources :contacts, except: [:show] do
    collection do
      get "autocomplete_contact_first_name" => "contacts#autocomplete_contact_first_name"
      get "autocomplete_tag_name" => "contacts#autocomplete_tag_name"
      get "add_phone_to_contact" => "contacts#add_phone_to_contact"
      get "add_email_to_contact" => "contacts#add_email_to_contact"
      get "destroy_phone/:phone_id" => "contacts#destroy_phone"
      get "destroy_email/:email_id" => "contacts#destroy_email"
      post "find_statuslabels" => "contacts#find_statuslabels"
      match 'view_all_notes/:id' => 'contacts#view_all_notes', as: "view_all_notes"
      match 'destroy_note/:note_id' => 'contacts#destroy_note', as: "destroy_note"
    end
  end
  
  # MANAGE PHONE CALLS
  scope '/manage_calls', defaults: {format: 'xml'} do
    match 'phone_script' => 'manage_phone_calls#phone_script', as: 'manage_phone_script'
    match 'phone_menu' => 'manage_phone_calls#phone_menu', as: 'manage_phone_menu'
    match 'voicemail' => 'manage_phone_calls#voicemail', as: 'manage_voicemail'
    match 'gather_digits' => 'manage_phone_calls#gather_digits'
    match 'record_call' => 'manage_phone_calls#record_call'
    match 'call_complete' => 'manage_phone_calls#call_complete', as: 'manage_call_complete'
    match 'download(/:id)' => 'call_recordings#download', as: :download_recording
  end

  # calendar paths
  scope '/calendar' do
    get '(/:year(/:month))', to: 'calendars#index', :as => :calendars, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
    match 'weekly(/:date)' => 'calendars#weekly', :as => :weekly
    get 'daily(/:date)' => 'calendars#daily', :as => :daily
  end
  resources :appointments, except: [:index, :show]

  # User change password after login
  get "users/edit_user_password" => "users#edit_user_password"

app/controllers/api/v1/partner_controller.rb
module Api
  module V1
    class PartnerController < ApplicationController
      respond_to :json
      skip_before_filter :logged_in, :set_defaults, :set_current_tenant

      def partner_detail
        coupon = DiscountMaster.find_by_coupon_code_and_active(params[:coupon_code],1)
        if coupon
          partner = coupon.partner_master
          if partner

            partner_landing = partner.partner_landing
            if partner_landing.present?
              content = partner_landing.content
            else
              content = ''
            end

            result = {success: true, partner_coupon_code: coupon.coupon_code, id: partner.id, first_name: partner.first_name, last_name: partner.last_name, content: content }
          else
            result = {success: false, message: 'Partner not found'}
          end
        else
          result = {success: false, message: 'Coupon not found'}
        end
        render json: result
      end

      def partner_logo
        coupon = DiscountMaster.find_by_coupon_code_and_active(params[:coupon_code],1)
        if coupon
          partner = coupon.partner_master
          if partner
            partner_logo = partner.partner_logo
            if partner_logo
              redirect_to ("#{root_url.chop}" + "#{partner_logo.logo.url}")
            else
              #render json: {success: false, message: 'Logo not found'}
              redirect_to ("#{root_url}default_logo.png")
            end
          else
            render json: {success: false, message: 'Partner not found'}
          end
        else
          render json: {success: false, message: 'Coupon not found'}
        end
      end
      def partner_landing_page_click
        coupon = DiscountMaster.find_by_coupon_code_and_active(params[:coupon_code],1)
        if coupon
          partner = coupon.partner_master_id
          if partner
            partner_state = PartnerStat.find_by_ip_address_and_partner_master_id(params[:ip_address], coupon.partner_master_id)
              if partner_state.present?
                partner_state.increment!(:clicks)
                render json: {success: true, message: 'partner state updated'}
              else
                partner_state = PartnerStat.create(:ip_address => params[:ip_address], :partner_master_id => coupon.partner_master_id, :clicks => 1)
                render json: {success: true, message: 'partner state created'}
              end
          else
            render json: {success: false, message: 'Partner not found'}
          end
        else
          render json: {success: false, message: 'Coupon not found'}
        end  
      end

    end
  end
end

app/controllers/partners/account_controller.rb
class Partners::AccountController < ApplicationController
  layout 'partners'
  # PAYMENT_TYPE = {"PAYPAL"=>"PAYPAL" , "BY CHECK" => "BY CHECK"}
  before_filter :check_doc_sign

  def index
    @paypal_type = ["PAYPAL", "BY CHECK"]
    @partner_master = PartnerMaster.find(params[:id])
    @partner_master.phone_number || @partner_master.build_phone_number
    @partner_master.address || @partner_master.build_address
    @paypal_info = PartnerPaymentInformation.find_by_partner_master_id(@partner_master.id) || PartnerPaymentInformation.new
  end

  def update
    @partner_master = PartnerMaster.find(params[:partner_master][:id])
    if params[:us_state].present?
      params[:partner_master][:address_attributes][:state] = params[:us_state]
    elsif params[:ca_state].present?
      params[:partner_master][:address_attributes][:state] = params[:ca_state]
    elsif params[:other_state].present?
      params[:partner_master][:address_attributes][:state] = params[:other_state]
    end

    if @partner_master.update_attributes!(params[:partner_master])
      redirect_to partners_account_index_path(id: params[:partner_master][:id]), notice: "Your account information saved successfully"
    else
      render :index
    end
    if params[:payment_type].present?
      @paypal_info = PartnerPaymentInformation.find_by_partner_master_id(params[:partner_master][:id])
      if @paypal_info.present?
        @paypal_info = @paypal_info.update_attributes(:payment_type => params[:payment_type], :paypal_email => params[:partner_payment_information][:paypal_email])
      else
        @paypal_info = PartnerPaymentInformation.create(:partner_master_id => params[:partner_master][:id], :payment_type => params[:payment_type], :paypal_email => params[:partner_payment_information][:paypal_email])
      end
    end
  end

  def verify_paypal_account
    respond_to do |format|
      format.json { render :json => PaypalApi.verify_paypal_account(params[:paypal_email]).success? }
    end
  end

  private

  def check_doc_sign
    if !current_partner_master.doc_sign
      flash[:alert] = "Please execute the partnership agreement to proceed. If you have any query, contact to YesTrak support team at support@yestrak.com"
      redirect_to partners_partner_docusign_index_path
    end
  end
end

app/controllers/partners/partner_helps_controller.rb
class Partners::PartnerHelpsController < ApplicationController
	layout 'partners'
	def index
    @partner_help = PartnerHelp.new
    render "new"
  end

  def new
  end

  def create
    params[:partner_help][:partner_master_id] = current_partner_master.id
    @partner_help = PartnerHelp.new(params[:partner_help])
    if @partner_help.save
      # =========== M A I L E R ============
      ClientMailer.partner_help_notice(@partner_help.id).deliver
      # =========== M A I L E R ============

      redirect_to partners_help_confirmation_path, notice: "We just received your question. A YesTrak representative will be in touch shortly with an answer."
    else
      render :new
    end
  end

  def help_confirmation
  end
end

app/helpers/partners/account_helper.rb
module Partners::AccountHelper
end

app/helpers/partners/custom_links_helper.rb
module Partners::CustomLinksHelper
end

app/helpers/partners/dashboard_helper.rb
module Partners::DashboardHelper
end

app/helpers/partners/partner_docusign_helper.rb
module Partners::PartnerDocusignHelper
end

app/helpers/partners/partner_helps_helper.rb
module Partners::PartnerHelpsHelper
end

app/helpers/partners/statements_helper.rb
module Partners::StatementsHelper
	
  def partner_statement_no_records
    concat content_tag(:section, class: 'table_row') {
      content_tag(:div, class: 'no_data') {
        content_tag(:div, 'No Records Found')
      }
    }
  end

end

app/helpers/partners/stats_helper.rb
module Partners::StatsHelper
	def partner_state_no_records
    haml_tag :table do
      haml_tag :tr do
        haml_tag :td, {:class => 'cell'} do
          haml_tag :td do
            haml_concat "No Record Found"
          end
        end
    end
  end
  end
end

app/views/partners/account/index.html.haml
%section.container
  %section.container_wrapper.graphpage
    %section.columns.clearfix
      %section.column.col-34
        = form_for @partner_master, html: {id: :frm_update_partner_master}, url: partners_account_update_path(@partner_master.id) do |f|
          = f.hidden_field :id
          %section.billingInfo
            %h2 PARTNER PROFILE
            %section.billingForm
              %ul
                %li{style: "margin-bottom: 0px"}
                  %label.account_label First Name:
                  = f.text_field :first_name, placeholder: "First Name", class: :inputBar
                %li
                  %label.account_label Last Name:
                  = f.text_field :last_name, placeholder: "Last Name", class: :inputBar
                = f.fields_for :phone_number do |phone_number|
                  %li.phoneNumberInputbar{style: "margin-bottom: 0px"}
                    %label.account_label Phone Number:
                    %table{:border => "0", :cellpadding => "0", :cellspacing => "0"}
                      %tr
                        %td.cal20 (
                        %td.cal50
                          = phone_number.text_field :area_code, placeholder: "123", maxlength: 3, class: "account_short"
                        %td.cal20 )
                        %td.cal50
                          = phone_number.text_field :phone1, placeholder: "456", maxlength: 3, class: "account_short"
                        %td.cal20 -
                        %td.cal75
                          = phone_number.text_field :phone2, placeholder: "7890", maxlength: 4, class: "account_short"
                %li
                  %label.account_label Email:
                  = f.text_field :email, placeholder: "Email", class: :inputBar
                = f.fields_for :address do |address|
                  %li{style: "margin-bottom: 0px"}
                    %label.account_label Street Address:
                    = address.text_field :street, placeholder: "1224 Happy Lane", class: :inputBar
                  %li
                    %label.account_label Suite/Floor:
                    = address.text_field :suite, placeholder: "1st floor", class: :inputBar
                  %li.phoneNumberInputbar{style: "margin-bottom: 0px"}
                    %label.account_label Country:
                    = address.select(:country, COUNTRIES.collect {|p| [ p.last, p.first ] },{prompt: 'Select Country'}, class: 'selectBar account_select')
                  %li
                    %label.account_label City:
                    = address.text_field :city, placeholder: "Schaumburg", class: :inputBar
                  %li.phoneNumberInputbar
                    %label.account_label State/Province:
                    = select_tag(:us_state, options_for_select(US_STATES.collect {|p| [ p.last, p.first ] },@partner_master.address.state),{prompt: 'Select State/Province', class: 'selectBar us_states account_select', style: "display: #{@partner_master.address.country.eql?('US') ? 'block' : 'none'};"})
                    = select_tag(:ca_state, options_for_select(CA_STATES.collect {|p| [ p.last, p.first ] },@partner_master.address.state),{prompt: 'Select State/Province', class: 'selectBar ca_states account_select', style: "display: #{@partner_master.address.country.eql?('CA') ? 'block' : 'none'};"})
                    = text_field_tag :other_state, (@partner_master.address.country.eql?('US') || @partner_master.address.country.eql?('CA')) ? '' : @partner_master.address.state, class: 'inputBar other_states', style: "display: #{(@partner_master.address.country.eql?('US') || @partner_master.address.country.eql?('CA')) ? 'none' : 'block'};"
                  %li
                    %label.account_label Zip/Postal Code:
                    = address.text_field :zip_code, placeholder: "60166", class: :inputBar
          = form_for @paypal_info, html: {id: :frm_update_paypa_info}, url: partners_account_update_path(@partner_master.id) do |form|
            %section.billingInfo
              %h2 PAYMENT  DISTRIBUTION
              %section.billingForm
                %ul
                  %li
                    %label.account_label Preferred method of payment:
                    = select_tag(:payment_type, options_for_select(@paypal_type.map {|type|  [type]}, @paypal_info.payment_type),{prompt: 'Select Type of Payment', class: 'selectBar us_states account_select'})
                  %li
                    %label.account_label PayPal Email:
                    = form.text_field :paypal_email, placeholder: "Email", class: :inputBar
                  %li
                    %label.account_label SSN / Tax ID:
                    = form.text_field :ssn_for_us, class: :inputBar
                  %li
                    %label.account_label SSN / Tax ID:
                    = form.text_field :ssn_for_non_us, class: :inputBar
            %section.form_action
              %ul
                %li
                  = link_to "Save", "javascript:;", disable_with: 'Wait..', :class => "save_btn", onclick: "frm_validate_partner_master()"
                  =# f.button "Save", disable_with: 'Wait..'