config/routes.rb
    devise_scope :partner_master do
      put "/confirm" => "confirmations#confirm"
    end

    namespace :partners do
      resources :dashboard do
        collection do
          match 'upload_logo' => "dashboard#upload_logo"
        end
      end
      resources :stats do
        collection do
          match "daterange_selector" => "stats#daterange_selector", as: "daterange_selector"
        end
      end

      resources :statements do #, only: [:index]
        collection do
          match "daterange_selector" => "statements#daterange_selector", as: "daterange_selector"
          post "paid_commission/:commission_id" => "statements#paid_commission", as: "paid_commission"
          post "paid_bonus" => "statements#paid_bonus", as: "paid_bonus"
  
        end
      end
      resources :account do
        match 'update' => "account#update"
        get :verify_paypal_account
      end
      resources :custom_links, only: [:index] do
        collection do
          match "edit_partner_page" => "custom_links#edit_partner_page", as: "edit_partner_page"
        end
      end
      resources :partner_docusign do
        collection do
          match 'upload_agreement' => 'partner_docusign#upload_agreement'
          match 'embedded_signing' => "partner_docusign#embedded_signing"
          match 'docusign_response' => "partner_docusign#docusign_response"
        end
      end
      resources :partner_helps
      match 'help_confirmation' => 'partner_helps#help_confirmation'
    end

    # Partner User change password after login
    get "partner_users/edit_user_password" => "partner_users#edit_user_password"
    post "partner_users/update_user_password" => "partner_users#update_user_password"
    get "partner_users/login/:auth_token" => "partner_users#login", as: 'login_from_admin_site'

    match "partner_users/check_current_password" => "partner_users#check_current_password"

    root :to => "partners/dashboard#index"
  end

  constraints :subdomain => ADMIN_SUBDOMAIN do
    ActiveAdmin.routes(self)
    devise_for :admin_users, ActiveAdmin::Devise.config.merge(:path => '')
    resources :recordings do
      member do
        get 'admin_download'
      end
    end
  end

  get "tags/index"
  # devise_for :users, controllers: {sessions: "sessions"}
  # API controllers for wordpress marketing site 
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1 do
      scope '/blog_details' do
        post 'fetch_blog_details' => 'blog_details#fetch_blog_details'
        post 'delete_blog_detail' => 'blog_details#delete_blog_detail'
      end
      scope '/contacts' do
        match 'create' => 'contacts#create'
      end
      scope 'subscription' do
        match 'create' => 'subscription#create'
        match 'validate_email' => 'subscription#validate_email'
        match 'discount_amount' => 'subscription#discount_amount'
      end
      scope 'partner' do
         match 'partner_detail' => 'partner#partner_detail'
         match 'partner_logo' => 'partner#partner_logo'
         match 'partner_landing_page_click' => 'partner#partner_landing_page_click'
      end
    end
  end

  scope '/webhooks' do
    post '/process' => 'webhooks#handle' #, :as => :process_webhook, :via => :post
    get '/process' => 'webhooks#verify' #, :as => :verify_webhook, :via => :get
  end

  # Settings allowed to owner or admin
  namespace :settings do
    resources :dashboard, only: [:index]
    resources :businesses, except: [:show] do
      collection do
        match "check_business_name" => "businesses#check_business_name"
      end
    end
    resources :phone_scripts, except: [:show] do
      member do
        get 'pick_number'
        put 'choose_number'
        post 'search_local_number'
        post 'search_tollfree_number'
        get 'set_script'
        put 'update_script'
        put 'complete'
        get 'routing_notification'
      end
      get 'check_for_uniq_name', on: :collection
    end
    resources :voicemails, except: [:show] do
      member do
        get 'pick_number'
        put 'choose_number'
        post 'search_local_number'
        post 'search_tollfree_number'
      end
      get 'check_for_uniq_name', on: :collection
    end
    resources :phone_menus, except: [:show] do
      member do
        get 'pick_number'
        put 'choose_number'
        post 'search_local_number'
        post 'search_tollfree_number'
      end
      get 'check_for_uniq_name', on: :collection
    end
    resources :call_recordings, only: [:index] do
      put 'update_recordings', on: :collection
    end
    resources :calendars, except: [:show] do
      collection do
        match "add_appointment_details" => "calendars#add_appointment_detail"
        match "check_duplicate_name" => "calendars#check_duplicate_name"
        match :remove_calendar_hour
        match "ical" => "calendars#ical", as: :ical
      end
    end
    resources :contacts, except: [:show] do
      # get :autocomplete_note_name, :on => :collection
      collection do
        # match "save_contact_settings" => "contacts#create_contact_settings", as: "save"
        match "add_status_label" => "contacts#add_status_label"
        match "add_tag" => "contacts#add_tag"
        get "delete_status/:id" => "contacts#delete_status"
        get :export_contacts
      end
    end
    resources :users, except: [:show] do
      collection do
        match "check_duplicate_email" => "users#check_duplicate_email"
        match "my_account" => "users#my_account"
        get :user_cancellation
        post :cancellation
        post :submit_suggestion
      end
    end
    resources :billings, except: [:show] do
      collection do
        match "upgrade_downgrade" => "billings#upgrade_downgrade"
        match "view_all_payments" => "billings#view_all_payments"
        match "view_invoice/:id" => "billings#view_invoice", as: :view_invoice
        match "download_invoice" => "billings#download_invoice"
      end
    end
  end
  
  resources :voicemail do
    collection do
      match "daterange_selector" => "voicemail#daterange_selector", as: "daterange_selector"
    end
  end
  # Calendar view
  resources :calendars, except: [:show] do
    collection do
      post :appoint_view
      get :appointment_view_month
      get :appointment_view_week
      get :appointment_day
      get :block_timing_modification
      post :list_calendars_appointments
    end
  end
  scope :calendars do
    get '(/:year(/:month))', to: 'calendars#index', :as => :calendars, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
    match 'weekly(/:date)' => 'calendars#weekly', :as => :weekly
    get 'daily(/:date)' => 'calendars#daily', :as => :daily
  end

  # Google Sync
  match "/auth/:provider/callback" => "calendars#google_sync"
  match "cancel_google_sync" => 'calendars#cancel_google_sync', as: :cancel_google_sync

  # Appointments
  resources :appointments do
    match 'get_contact_detail/:contact_id' => 'appointments#get_contact_detail', as: :get_contact_detail
    collection do
      match "is_valid_time" => "appointments#is_valid_time"
    end
  end

  # Dashboard notification
  resources :notifications, only: [:index] do
    collection do
      match "daterange_selector" => "notifications#daterange_selector", as: "daterange_selector"
      match "create_user_notification_entry" => "notifications#create_user_notification_entry"
    end
  end

  resources :registrations, only: [:index] do
    collection do
      # get "rejoin/:auth_token" => "registrations#rejoin", as: "rejoin"
      get :rejoin
      post :process_rejoin
      post :check_coupen
    end
  end


  resources :call_recordings do
    collection do
      match "daterange_selector" => "call_recordings#daterange_selector", as: "daterange_selector"
    end
  end

  match 'voicemail/:sid' => 'call_recordings#voicemail', as: 'voicemail_recording'
  match 'voicemail_test/:sid' => 'call_recordings#voicemail_test'

  # Contacts display
  resources :contacts, except: [:show] do
    collection do
      get "autocomplete_contact_first_name" => "contacts#autocomplete_contact_first_name"
      get "autocomplete_tag_name" => "contacts#autocomplete_tag_name"
      get "add_phone_to_contact" => "contacts#add_phone_to_contact"
      get "add_email_to_contact" => "contacts#add_email_to_contact"
      get "destroy_phone/:phone_id" => "contacts#destroy_phone"
      get "destroy_email/:email_id" => "contacts#destroy_email"
      post "find_statuslabels" => "contacts#find_statuslabels"
      match 'view_all_notes/:id' => 'contacts#view_all_notes', as: "view_all_notes"
      match 'destroy_note/:note_id' => 'contacts#destroy_note', as: "destroy_note"
    end
  end
  
  # MANAGE PHONE CALLS
  scope '/manage_calls', defaults: {format: 'xml'} do
    match 'phone_script' => 'manage_phone_calls#phone_script', as: 'manage_phone_script'
    match 'phone_menu' => 'manage_phone_calls#phone_menu', as: 'manage_phone_menu'
    match 'voicemail' => 'manage_phone_calls#voicemail', as: 'manage_voicemail'
    match 'gather_digits' => 'manage_phone_calls#gather_digits'
    match 'record_call' => 'manage_phone_calls#record_call'
    match 'call_complete' => 'manage_phone_calls#call_complete', as: 'manage_call_complete'
    match 'download(/:id)' => 'call_recordings#download', as: :download_recording
  end

  # calendar paths
  scope '/calendar' do
    get '(/:year(/:month))', to: 'calendars#index', :as => :calendars, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
    match 'weekly(/:date)' => 'calendars#weekly', :as => :weekly
    get 'daily(/:date)' => 'calendars#daily', :as => :daily
  end
  resources :appointments, except: [:index, :show]

  # User change password after login
  get "users/edit_user_password" => "users#edit_user_password"
  get "users/login/:auth_token" => "users#login", as: 'login_from_admin'
  post "users/update_user_password" => "users#update_user_password"

app/controllers/settings/businesses_controller.rb
module Settings
  class BusinessesController < ApplicationController
    load_and_authorize_resource

    add_breadcrumb "Settings", :settings_dashboard_index_path

    def index
      @business = Business.includes(:address).includes(:phone_number).all
    end

    def new
      @business = Business.new
      @business.build_address
      @business.build_phone_number
      add_breadcrumb "Businesses", settings_businesses_path
    end

    def create
      @business = Business.new(params[:business])

      if params[:us_state].present?
        @business.address.state = params[:us_state]
      elsif params[:ca_state].present?
        @business.address.state = params[:ca_state]
      elsif params[:other_state].present?
        @business.address.state = params[:other_state]
      end

      if @business.save
        ClientMailer.delay.business_created(@business)
        @business.notifications.create(title: 'A new business was added to your account', notify_on: Time.now,
           content: "<span>The new business #{@business.name} was created by #{current_user.full_name} and is now available for use.</span>")
        redirect_to settings_businesses_path, notice: "Business saved successfully"
      else
        render :new
      end
    end

    def edit
      @business = Business.find(params[:id])
      add_breadcrumb "Businesses", settings_businesses_path
    end

    def update
      @business = Business.find(params[:business][:id])

      if params[:us_state].present?
        params[:business][:address_attributes][:state] = params[:us_state]
      elsif params[:ca_state].present?
        params[:business][:address_attributes][:state] = params[:ca_state]
      elsif params[:other_state].present?
        params[:business][:address_attributes][:state] = params[:other_state]
      end

      if @business.update_attributes(params[:business])
        ClientMailer.delay.business_updated(@business)
        @business.notifications.create(title: 'A business was edited', notify_on: Time.now,
          content: "<span>The business #{@business.name} was edited by #{current_user.full_name}.</span>")
        redirect_to settings_businesses_path, notice: "Business saved successfully"
      else
        render :edit
      end
    end

    def destroy
      @business = Business.find(params[:id])
      @notification_business = Business.find(params[:id])
      ClientMailer.delay.business_deleted(@business)
      @business.destroy

      @notification_business.notifications.create(title: 'A business was deleted', notify_on: Time.now,
        content: "<span>The business #{@notification_business.name} was deleted by #{current_user.full_name}. All scripts or calendars related to this business have been affected; be sure to resolve any inconsistencies related to these orphans.</span>")
      redirect_to settings_businesses_path, notice: "Business deleted successfully"
    end

    # check for duplicate business name when we try to use from jQuery validations
    def check_business_name
      if params[:business_id].present?
        @business = Business.where("name = ? and id != ? ", params[:business][:name], params[:business_id]).present?
      else
        @business = Business.where("name = ?", params[:business][:name]).present?
      end
      respond_to do |format|
       format.json { render :json => !@business }
      end
    end
  end
end

app/controllers/settings/dashboard_controller.rb
class Settings::DashboardController < ApplicationController

  before_filter :check_super_user

  def index
  end

  private ############################

  def check_super_user
    #redirect_to root_path, alert: 'Unauthorized' if current_tenant.is_inactive?
    redirect_to root_path, alert: 'Unauthorized' unless current_user.is_super_user?
  end

end

app/helpers/settings/billings_helper.rb
module Settings::BillingsHelper
  def service_item(billing_transaction)
    item_label = ''
    if !billing_transaction.billable_type.nil? && billing_transaction.billable_type.include?("Tenant")
      #tenant = Tenant.find(billing_transaction.billable_id).plan_bid
      if billing_transaction.subscription_id.present?
        subscription_plan = Subscription.find(billing_transaction.subscription_id).plan_bid
        if subscription_plan == "500minutes"
          item_label = "500 Minute Plan"
        elsif subscription_plan == "200minutes"
          item_label = "200 Minute Plan"
        else
          item_label = "Pay As You Go"
        end
      end
    elsif !billing_transaction.billable_type.nil? && billing_transaction.billable_type.include?("AddOn")
      add_on = AddOn.find(billing_transaction.billable_id).type_of
      if add_on == AddOn::TYPE_OF[2]
        item_label = "Call Recording"
      elsif add_on == AddOn::TYPE_OF[1]
        item_label = "Phone Menu"
      elsif add_on == AddOn::TYPE_OF[0]
        item_label = "Voicemail"
      end
    elsif !billing_transaction.billable_type.nil?
      item_label = billing_transaction.billable_type.to_s
    end
    return item_label
  end

  def service_name(transaction)
    case transaction.chargeable_type
      when 'Voicemail', 'PhoneMenu'
        "#{transaction.chargeable_type}(#{transaction.chargeable.name})"
      when 'CallCharge'
        "#{transaction.chargeable_type}(#{transaction.chargeable.call_type} Calls)"
      else
        transaction.chargeable_type
    end
  end

  def get_rate(transaction, plan)
    case transaction.chargeable.call_type
      when 'Voicemail', 'PhoneMenu'
        PackageConfig::OVERAGE[PackageConfig::ADD_ON_SERVICE]
      when 'PhoneScript'
        PackageConfig::OVERAGE[plan]
    end
  end

end

app/helpers/settings/businesses_helper.rb
module Settings::BusinessesHelper
end

app/helpers/settings/calendars_helper.rb
module Settings::CalendarsHelper
end

app/helpers/settings/call_recordings_helper.rb
module Settings::CallRecordingsHelper
end

app/helpers/settings/contacts_helper.rb
module Settings::ContactsHelper
end

app/helpers/settings/dashboard_helper.rb
module Settings::DashboardHelper
end

app/helpers/settings/phone_menues_helper.rb
module Settings::PhoneMenuesHelper
end

app/helpers/settings/phone_scripts_helper.rb
module Settings::PhoneScriptsHelper

  def print_phone_line(friendly_name)
    friendly_name.sub(')','-').sub('(','+1 ')
  end

  def highlight_number(number, area_code, keyword)
    content = ''
    if area_code.present?
      content += "<u>#{number[0..2]}</u>"
      number = number[3..-1]
    end
    if keyword.present?
      content += number.gsub(/(?<i>#{keyword})/, '<u>\k<i></u>')
    else
      content += number
    end
    content.html_safe
  end

end

app/views/settings/voicemails/_form.html.haml
/ bof page title
%section.page_title
  Voicemail Boxes
/eof page title

/ bof Voicemail Boxes Edit
%section.voicemail-boxes-edit
  = nested_form_for [:settings, @voicemail], html: {id: :phone_script_form} do |f|
    %section.voicemail_name
      %label What business are your callers calling?
      = f.collection_select :business_id, @businesses, :id, :name, prompt: 'Select business name'
    %section.voicemail_name
      %label What would you like to name this voicemail box?
      = f.hidden_field :id
      = f.text_field :name
    %section.voicemail_recordings
      %label Where would you like the recordings of the voicemail messages sent to?
      - flag = true
      %ul#email_id_fields
        = f.fields_for :email_ids, :wrapper => false do |email|
          %li.remove_email_id
            = email.email_field :emails, class: 'email_input', placeholder: 'Email id'
            - if flag
              = f.link_to_add image_tag( "btn_plus@2x.png", width: '19'), :email_ids, data: { target: "#email_id_fields", nested_wrapper_class: 'email_ids-wrapper' },
                 style: (@voicemail.email_ids.size >= TOTAL_SMS_EMAIL) ? 'display: none' : ''
            - else
              = email.link_to_remove image_tag( "btn_close@2x.png", width: '19'), id: 'remove_email_id'
            - flag = false
      %br
      %label SMS/Text
      - flag = true
      %ul#notify_numbers
        = f.fields_for :notify_numbers, :wrapper => false do |sms|
          %li.remove_notify_number
            %table{:border => "0", :cellpadding => "0", :cellspacing => "0"}
              %tr
                %td.call15 (
                %td.call50
                  = sms.text_field :area_code, class: 'inputBar sms_input', maxlength: 3
                %td.call15 )
                %td.call50
                  = sms.text_field :phone1, class: 'inputBar sms_input', maxlength: 3
                %td.call15 -
                %td.call50
                  = sms.text_field :phone2, class: 'inputBar sms_input', maxlength: 4
                %td.call25
                  - if flag
                    = f.link_to_add image_tag( "btn_plus@2x.png", width: '19'), :notify_numbers, :data => { :target => "#notify_numbers" },
                      style: (@voicemail.notify_numbers.size >= TOTAL_SMS_EMAIL) ? 'display: none' : ''
                  - else
                    = sms.link_to_remove image_tag( "btn_close@2x.png", width: '19'), id: 'remove_notify_number'
                  - flag = false
    -#%section.voicemail_transcribed
    -#  %label Would you like your voicemail messages transcribed?
    -#  %ul
    -#    %li
    -#      = f.radio_button(:transcribe, true)
    -#      = f.label(:transcribe, 'Yes', value: 'true')
    -#    %li
    -#      = f.radio_button(:transcribe, false)
    -#      = f.label(:transcribe, 'No', value: 'false')
    %section.voicemail_upload
      %label Upload the audio file for your voicemail greeting here:
      %div.upload_file
        = f.fields_for :audio_file do |audio|
          .audio_player
            %audio#default_audio{:controls => "control", :preload => "none", :src => @voicemail.audio_file.try(:record), :type => "audio/x-m4a"}
          = audio.file_field :record, value: @voicemail.audio_file.try(:record_file_name)
        %p NOTE: Acceptable formats are .wav or MP3 files.
    %section.form_action
      %ul
        %li
          = link_to raw("<span>Previous</span>"), settings_voicemails_path, :class => "prev_btn"
        %li
          -#= f.submit 'Save', disable_with: 'Wait..'
          = f.button 'Save', disable_with: 'Wait..', :class => "save_btn"
/ eof Voicemail Boxes Edit

app/views/settings/voicemails/_phone_number.html.haml
/ bof page title
%section.page_title
  Pick a Number
/ eof page title

/ bof pick number Boxes
%section.pick-number
  %section.current_number
    %label The current phone number for this voicemail box is:
    %input{name: "", value: "+1 646-736-6529", type: "text"}

  %section.swap_number
    %span Do you need to swap out this phone number?
    %ul
      %li
        %input{name: "", type: "checkbox", value: "no"} <label>No</label>
      %li
        %input{name:"", type: "checkbox", value: "yes"} <label>Yes</label>

  %p.pnBox
    Pick a new phone number for this voicemail box:
    %span (This is where callers will be routed to hear your voicemail box).

  %div#tab-container.tab-container
    %ul.etabs
      %li.tab
        %a{href: "#local"} Local
      %li.tab
        %a{href: "#toll-free"} Toll-Free

    %div#local.panel-container
      %div.search_number
        %form.search_phone_number
          %div.search_phone_number_input
            %select.area_code_sign{name: ""}
              %option #
              %option +

            %div.phone_wrapper
              %table{border: "0", cellspacing: "0", cellpadding: "0"}
                %tr
                  %td{style: "width:10px;"} (
                  %td.area_code
                    %input{name: "", type: "text"}
                  %td{style: "width:10px;"} )
                  %td.digits_phrases
                    %input{name: "", type: "text"}

          %input.btn_search{name: "Search", type: "button", value: "Search"}
          %div.search_notes Search by area code, digits and phrases

        %div.clearfix
          %div.area_code_notes
            %h2
              Area code
              %span Enter the entire area code.
            -#%p Don’t know an area code? Search by location instead.

          %div.digits_phrases_notes
            %h2
              Digits &amp; phrases
              %span Enter at least three characters to search for a specific pattern.
            %p Tip: Get more results with shorter patterns.

    / content
    %div#toll-free{style: "display:none;", class: "panel-container"}
      %div.search_number
        %form.search_phone_number
          %div.search_phone_number_input
            %select.area_code_sign{name: ""}
              %option #
              %option +

            %div.phone_wrapper
              %table{border: "0", cellspacing: "0", cellpadding: "0"}
                %tr
                  %td{style: "width:10px;"} (
                  %td.area_code
                    %input{name: "", type: "text"}
                  %td{style: "width:10px;"} )
                  %td.digits_phrases
                    %input{name: "", type: "text"}

          %input.btn_search{name: "Search", type: "button", value: "Search"}
          %div.search_notes Search by area code, digits and phrases

        %div.clearfix
          %div.area_code_notes
            %h2
              Area code
              %span Enter the entire area code.
            -#%p Don’t know an area code? Search by location instead.

          %div.digits_phrases_notes
            %h2
              Digits &amp; phrases
              %span Enter at least three characters to search for a specific pattern.
            %p Tip: Get more results with shorter patterns.
    / content

  / bof Displaying results
  %section.displaying_results
    %h1
      Displaying results for >>
      %span 646
      in
      %span United States
    %ul
      %li
        %div.result_punber
          +1 646-736-6529
          %span
            %i
              +1<u>646</u>7366529
            %b NEW YORK, NY
        %div.btn_process_swap
          %a{href: "#"} PROCESS SWAP
      %li
        %div.result_punber
          +1 646-736-6529
          %span
            %i
              +1<u>646</u>7366529
            %b NEW YORK, NY
        %div.btn_process_swap
          %a{href: "#"} PROCESS SWAP
      %li
        %div.result_punber
          +1 646-736-6529
          %span
            %i
              +1<u>646</u>7366529
            %b NEW YORK, NY
        %div.btn_process_swap
          %a{href: "#"} PROCESS SWAP
      %li
        %div.result_punber
          +1 646-736-6529
          %span
            %i
              +1<u>646</u>7366529
            %b NEW YORK, NY
        %div.btn_process_swap
          %a{href: "#"} PROCESS SWAP
      %li
        %div.result_punber
          +1 646-736-6529
          %span
            %i
              +1<u>646</u>7366529
            %b NEW YORK, NY
        %div.btn_process_swap
          %a{href: "#"} PROCESS SWAP
      %li
        %div.result_punber
          +1 646-736-6529
          %span
            %i
              +1<u>646</u>7366529
            %b NEW YORK, NY
        %div.btn_process_swap
          %a{href: "#"} PROCESS SWAP
      %li
        %div.result_punber
          +1 646-736-6529
          %span
            %i
              +1<u>646</u>7366529
            %b NEW YORK, NY
        %div.btn_process_swap
          %a{href: "#"} PROCESS SWAP
      %li
        %div.result_punber
          +1 646-736-6529
          %span
            %i
              +1<u>646</u>7366529
            %b NEW YORK, NY
        %div.btn_process_swap
          %a{href: "#"} PROCESS SWAP
      %li
        %div.result_punber
          +1 646-736-6529
          %span
            %i
              +1<u>646</u>7366529
            %b NEW YORK, NY
        %div.btn_process_swap
          %a{href: "#"} PROCESS SWAP
      %li
        %div.result_punber
          +1 646-736-6529
          %span
            %i
              +1<u>646</u>7366529
            %b NEW YORK, NY
        %div.btn_process_swap
          %a{href: "#"} PROCESS SWAP

    %div.btn_prev
      %a{href: "#"}
        %span
          = image_tag "arrow_left.png", alt: ""
        Previous
  / eof Displaying results
/ eof pick number Boxes

:javascript
  $(document).ready(function(){
    $(document).ready( function() {
        $('#tab-container').easytabs('animate:false', 'transitionIn:fadeIn');
      });
  });

app/views/settings/voicemails/edit.html.haml
= render 'form'

app/views/settings/voicemails/index.html.haml
/ bof page title
%section.page_title Voicemail Boxes
/eof page title

/ bof Voicemail Boxes
%section.voicemail-boxes
  %p.vmBox Here is a list of your current voicemail boxes:
  %section.list_voicemail
    %section.table_head
      %table{width: "100%", border: "0", cellspacing: "0", cellpadding: "0"}
        %tr
          %th{width: "32%"} Menu Name
          %th{width: "37%"} Phone Number
          %th{width: "31%"} Edit/Delete
    = render partial: 'settings/shared/index_table', locals: {phone_numbers: @voicemails}
    %section.table_body
      %table{width: "100%", border: "0", cellspacing: "0", cellpadding: "0"}
        %tr
          %td.menuName{width: "32%"} Add New Voicemail Box
          %td{width: "37%"} &nbsp;
          %td{width: "31%"}
            - if @free_voicemail
              = link_to "Add", new_settings_voicemail_path, class: "add"
            - else
              %span.priceBuy
                %b
                  $10/
                  %i month
                = link_to "Buy", new_settings_voicemail_path, data: { confirm: 'Are you sure want to buy Voicemail?' }
  %section.voicemailIncludeWrap
    .voicemailBox
      .boxIcon
        = image_tag "icon_voicemail@2x.png", :width => "115px"
      %h2 YesTrak Voicemail Boxes Include:
      %ul
        %li Quick and easy setup.
        %li Personalize the greeting in your own voice, and easily change it whenever necessary from your smartphone.
        %li Real-time notifications via text or email so you never miss an opportunity.
        %li Pick up messages your way — on the go, or at your desk.
/ eof Voicemail Boxes

app/views/settings/voicemails/new.html.haml
= render 'form'

app/views/settings/voicemails/pick_number.html.haml
/ bof page title
%section.page_title
  Pick a Number
  / eof page title
/ bof pick number Boxes
%section.pick-number
  %p.pnBox
    Pick a new phone number for this voicemail box:
    %span (This is where callers will be routed to receive your voicemail box).
  = render partial: 'settings/shared/search_number', locals: {phone_number: @voicemail, toll_free: true, swap: false}
  / bof Displaying results
  %section.displaying_results#displaying_results_local
  %section.displaying_results#displaying_results_tollfree
  / eof Displaying results
/ eof pick number Boxes
%section.form_action
  %ul
    %li
      = link_to raw('<span>Previous</span>'), edit_settings_voicemail_path(@voicemail), :class => "prev_btn"
/ eof container

app/views/settings/voicemails/swap_number.html.haml
/ bof page title
%section.page_title
  the phone number
/ eof page title
/ bof pick number Boxes
%section.pick-number
  %section.current_number
    %label The current phone number for this voicemail box is:
    = text_field_tag nil, @twilio_number.try(:print_phone_line), disabled: true
  %section.swap_number
    %span Do you need to swap out this phone number?
    %ul
      %li
        = radio_button_tag(:phone_number_swap, 'false', true)
        = label_tag(:phone_number_swap_false, 'No')
      %li
        = radio_button_tag(:phone_number_swap, 'true')
        = label_tag(:phone_number_swap_true, 'Yes')
  %p.pnBox
    If yes, please pick a new phone number for this voicemail box:
    -#%span (This is where callers will be routed to hear your voicemail box).
  = render partial: 'settings/shared/search_number', locals: {phone_number: @voicemail, toll_free: true, swap: true}
  / bof Displaying results
  %section.displaying_results#displaying_results_local
  %section.displaying_results#displaying_results_tollfree
  / eof Displaying results
  / eof pick number Boxes
%section.form_action
  %ul
    %li
      = link_to raw('<span>Previous</span>'), edit_settings_voicemail_path(@voicemail), :class => "prev_btn"
/ eof container

:javascript
  $(document).ready(function() {
    $("div#tab-container :input").attr("disabled", $('input#phone_number_swap_false').is(':checked'));
  });